### PR TITLE
Formalities (and testing system)

### PR DESCRIPTION
**Pull request by ibecav**
Adding a line to .gitignore to exclude my Rproj file

Adding myself as a contributor in DESCRIPTION

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
At this point, I am not comfortable with adding you as author (`"aut"`) of this package but will be happy to add you as a contributor (`"ctb"`).

As your contributions increase (especially in the form of new functions), I will be more than happy to add you as author and contributor (`c("ctb", "aut")`).

image

Is that okay with you?

**Comment by ibecav** [comment]
Perfect thanks I’ll make the change

**Comment by IndrajeetPatil** [comment]
Since merging the PR and pulling it to my local repo, the package build is no longer working for me and gives the following error:
```
ERROR: The build directory does not contain a DESCRIPTION
file so cannot be built as a package.

Build directory: ~/ggstatsplot
```

Do you know what happened?

**Comment by IndrajeetPatil** [comment]
I am reverting this PR because something is not right. I can no longer work on the package with this problem.

**Pull request merged**
