### PR TITLE
Outlierfix

### PR DESCRIPTION
**Pull request by ibecav**
see issue #101

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
@ibecav Can you just copy-paste the new tests I had added last night to your `test_ggbetweenstats.R` so that this merge conflict is resolved? Even if I edit the file here and resolve it, I am pretty sure some of the tests are going to fail because I had deliberately added tests to check how boxplot and violin builds are currently working (this is how discovered the #101 issue) and your solution is going to change their behavior.

**Comment by ibecav** [comment]
I'll see what I can do.  It is mildly frustrating though since I tried to tell you last night I was working on it.  If you'd rather handle it I'll happily step aside.

**Comment by IndrajeetPatil** [comment]
Yeah, I understand that and sorry about that. But I made the changes to test files and none of the `.R` files because I knew you were working on those. I wrote tests to **discover the problems** and **not implement any solutions** since I knew you were working on the latter and thought former could help. The only way I could tell that these problems were solved was by checking how the tests changed.

**Comment by ibecav** [comment]
Okay I got it as close as I could manually.  All your work is there some is commented and as we move down the road should be trivial to reimplement.

**Comment by IndrajeetPatil** [comment]
You will also have to update the `.Rd` files for the build to succeed.

**Comment by IndrajeetPatil** [comment]
Okay, although the CI builds are no longer failing, the code coverage checks don't pass. 

Is there any particular reason why some of the tests have been commented out?

**Comment by ibecav** [comment]
Yes because until I finish the whole set of changes these are likely to change some more and chasing the down right now is painful.

**Comment by IndrajeetPatil** [comment]
Can you include the whole set of changes in a single, major `PR`, just like you did for the `movies_long` and `movies_wide` datasets? 

It will be much easier for me to evaluate the changes to the function behavior when the final form of outlier labeling is clear. Right now, I am not happy with how the plot looks with this PR merged since the `ggrepel` labels are disembodied from the data points. I **know** that you are not done with the changes, but that by definition make this a "development branch" and it won't be prudent to merge this into `master` at this point.

I am currently at the aiport and will be traveling for the next few days and won't have the cognitive bandwidth to work on this, so no hurry.

**Comment by ibecav** [comment]
No thanks and for the record you only get the 'disembodied' look if you deliberately choose `outlier.tagging = TRUE` and `outlier.shape = NA` which I'll admit is a pretty silly thing for the user to choose to do and is unlikely to happen.

This PR as is at least gives you the ability to change outlier color and shape and has rational defaults.  It does not yet fix the other two semi-related problems:

1. It doesn't fix the problem that pure violin plots don't come with outliers to be labeled.
2. It doesn't fix the issue I dislike which is that the current version of the software "double plots" points which is entirely misleading to the eye.  See my original movies_long example where movies like Lord of the Rings are actually having two points plotted which is inaccurate and confusing.

Attached is a reprex showing current state with my PR and some rational examples.  Note that in plots 2 & 3 genus Didelphis is another example of the double plotting.  It makes it looks like there are two datapoints there when in fact there is onle one and dual appearance is simply the way we are calling the geoms_

Anyway, no interest in continuing if you won't accept incremental work that builds, passes the tests and losses coverage/coveralls — Coverage decreased (-0.003%) to 96.875% coverage temporarily.  By the way one of the by products of this PR is eliminating a section of unnecessary code because you're currently plotting the boxplot twice.

Happy to wait until you get back or simply step back and stop working altogether.

``` r
# default simplest
ggstatsplot::ggbetweenstats(
  data = ggplot2::msleep,
  x = vore,
  y = sleep_total)
#> Note: 95% CI for effect size estimate was computed with 100 bootstrap samples.
#> 
#> Note: Shapiro-Wilk Normality Test for sleep_total : p-value = 0.154
#> 
#> Note: Bartlett's test for homogeneity of variances for factor vore : p-value = 0.104
#> 
```



``` r

# just add labels
ggstatsplot::ggbetweenstats(
  data = ggplot2::msleep,
  x = vore,
  y = sleep_total,
  outlier.tagging = TRUE,
  outlier.label = genus
)
#> Note: 95% CI for effect size estimate was computed with 100 bootstrap samples.
#> 
#> Note: Shapiro-Wilk Normality Test for sleep_total : p-value = 0.154
#> 
#> Note: Bartlett's test for homogeneity of variances for factor vore : p-value = 0.104
#> 
```



``` r

# get fancier
ggstatsplot::ggbetweenstats(
  data = ggplot2::msleep,
  x = vore,
  y = sleep_total,
  outlier.tagging = TRUE,
  outlier.label = genus,
  outlier.color = "blue",
  outlier.shape = 15
)
#> Note: 95% CI for effect size estimate was computed with 100 bootstrap samples.
#> 
#> Note: Shapiro-Wilk Normality Test for sleep_total : p-value = 0.154
#> 
#> Note: Bartlett's test for homogeneity of variances for factor vore : p-value = 0.104
#> 
```



<sup>Created on 2018-12-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ibecav** [comment]
``` r
# Reprex putting all the oulier changes through their paces
# December 13 @ 3:49pm
library(ggstatsplot)
# plot
ggstatsplot::ggbetweenstats(
  data = ToothGrowth,
  x = supp,
  y = len,
  plot.type = "violin",
  messages = FALSE,
  results.subtitle = FALSE,
  outlier.tagging = TRUE,
  outlier.coef = 0.5,
  mean.plotting = FALSE,
  sample.size.label = FALSE
)
```



``` r

ggstatsplot::ggbetweenstats(
  data = ToothGrowth,
  x = supp,
  y = len,
  plot.type = "box",
  results.subtitle = FALSE,
  outlier.tagging = TRUE,
  outlier.coef = 0.5,
  outlier.color = "blue",
  messages = FALSE
)
```



``` r


ggstatsplot::ggbetweenstats(
  data = ToothGrowth,
  x = supp,
  y = len,
  plot.type = "boxviolin",
  results.subtitle = FALSE,
  outlier.tagging = TRUE,
  outlier.coef = 0.5,
  outlier.shape = 12,
  outlier.color = "blue",
  notch = TRUE,
  messages = FALSE
)
```



``` r

# works grouped
ggstatsplot::grouped_ggbetweenstats(
  data = ToothGrowth,
  x = supp,
  y = len,
  grouping.var = dose,
  plot.type = "violin",
  results.subtitle = FALSE,
  outlier.tagging = TRUE,
  outlier.coef = 0.5,
  outlier.color = "blue",
  messages = FALSE
)
```



``` r

# default simplest
ggstatsplot::ggbetweenstats(
  data = ggplot2::msleep,
  x = vore,
  y = sleep_total)
#> Note: 95% CI for effect size estimate was computed with 100 bootstrap samples.
#> 
#> Note: Shapiro-Wilk Normality Test for sleep_total : p-value = 0.154
#> 
#> Note: Bartlett's test for homogeneity of variances for factor vore : p-value = 0.104
#> 
```



``` r

# just add labels
ggstatsplot::ggbetweenstats(
  data = ggplot2::msleep,
  x = vore,
  y = sleep_total,
  outlier.tagging = TRUE,
  outlier.label = genus
)
#> Note: 95% CI for effect size estimate was computed with 100 bootstrap samples.
#> 
#> Note: Shapiro-Wilk Normality Test for sleep_total : p-value = 0.154
#> 
#> Note: Bartlett's test for homogeneity of variances for factor vore : p-value = 0.104
#> 
```



``` r

# works with violins too
ggstatsplot::ggbetweenstats(
  data = ggplot2::msleep,
  x = vore,
  y = sleep_total,
  plot.type = "violin",
  outlier.tagging = TRUE,
  outlier.label = genus
)
#> Note: 95% CI for effect size estimate was computed with 100 bootstrap samples.
#> 
#> Note: Shapiro-Wilk Normality Test for sleep_total : p-value = 0.154
#> 
#> Note: Bartlett's test for homogeneity of variances for factor vore : p-value = 0.104
#> 
```



``` r

# get fancier
ggstatsplot::ggbetweenstats(
  data = ggplot2::msleep,
  x = vore,
  y = sleep_total,
  outlier.tagging = TRUE,
  outlier.label = genus,
  outlier.color = "blue",
  outlier.shape = 15
)
#> Note: 95% CI for effect size estimate was computed with 100 bootstrap samples.
#> 
#> Note: Shapiro-Wilk Normality Test for sleep_total : p-value = 0.154
#> 
#> Note: Bartlett's test for homogeneity of variances for factor vore : p-value = 0.104
#> 
```



``` r

# pure box
ggstatsplot::ggbetweenstats(
  data = ggplot2::msleep,
  x = vore,
  y = sleep_total,
  outlier.tagging = TRUE,
  plot.type = "box",
  outlier.label = genus,
  outlier.color = "blue",
  outlier.shape = 15
)
#> Note: 95% CI for effect size estimate was computed with 100 bootstrap samples.
#> 
#> Note: Shapiro-Wilk Normality Test for sleep_total : p-value = 0.154
#> 
#> Note: Bartlett's test for homogeneity of variances for factor vore : p-value = 0.104
#> 
```



``` r

# back to violin changing shape and color
ggstatsplot::ggbetweenstats(
  data = ggplot2::msleep,
  x = vore,
  y = sleep_total,
  outlier.tagging = TRUE,
  plot.type = "violin",
  outlier.label = genus,
  outlier.color = "blue",
  outlier.shape = 15
)
#> Note: 95% CI for effect size estimate was computed with 100 bootstrap samples.
#> 
#> Note: Shapiro-Wilk Normality Test for sleep_total : p-value = 0.154
#> 
#> Note: Bartlett's test for homogeneity of variances for factor vore : p-value = 0.104
#> 
```



``` r

# both
ggstatsplot::ggbetweenstats(
  data = ggplot2::msleep,
  x = vore,
  y = sleep_total,
  outlier.tagging = TRUE,
  plot.type = "boxviolin",
  outlier.label = genus,
  outlier.color = "blue",
  outlier.shape = 15
)
#> Note: 95% CI for effect size estimate was computed with 100 bootstrap samples.
#> 
#> Note: Shapiro-Wilk Normality Test for sleep_total : p-value = 0.154
#> 
#> Note: Bartlett's test for homogeneity of variances for factor vore : p-value = 0.104
#> 
```



``` r

# and of course my original issue on a large dataset
# box
ggstatsplot::ggbetweenstats(
  data = movies_long,
  x = mpaa,
  y = rating,
  plot.type = "box",
  conf.level = 0.99,
  xlab = "MPAA Rating",
  ylab = "IMDB Rating",
  pairwise.comparisons = TRUE,
  pairwise.annotation = "p.value",
  p.adjust.method = "fdr",
  outlier.tagging = TRUE,
  outlier.label = title,
  nboot = 10,
  ggtheme = ggthemes::theme_few(),
  ggstatsplot.layer = FALSE,
  bf.message = TRUE
)
#> Note: 99% CI for effect size estimate was computed with 10 bootstrap samples.
#> 
#> # tibble [3 × 11]
#>   group1 group2 mean.difference conf.low conf.high    se t.value    df
#>   <chr>  <chr>            <dbl>    <dbl>     <dbl> <dbl>   <dbl> <dbl>
#> 1 R      PG-13           -0.219   -0.375    -0.064 0.047   3.31  1142.
#> 2 R      PG              -0.323   -0.573    -0.074 0.075   3.05   277.
#> 3 PG-13  PG              -0.104   -0.362     0.154 0.077   0.952  309.
#> # ... with 3 more variables: p.value <dbl>, significance <chr>,
#> #   p.value.label <chr>
#> Note: Shapiro-Wilk Normality Test for rating : p-value = < 0.001
#> 
#> Note: Bartlett's test for homogeneity of variances for factor mpaa : p-value = 0.004
#> 
```



``` r

# violin
ggstatsplot::ggbetweenstats(
  data = movies_long,
  x = mpaa,
  y = rating,
  plot.type = "violin",
  conf.level = 0.99,
  xlab = "MPAA Rating",
  ylab = "IMDB Rating",
  pairwise.comparisons = TRUE,
  pairwise.annotation = "p.value",
  p.adjust.method = "fdr",
  outlier.tagging = TRUE,
  outlier.label = title,
  nboot = 10,
  ggtheme = ggthemes::theme_few(),
  ggstatsplot.layer = FALSE,
  bf.message = TRUE
)
#> Note: 99% CI for effect size estimate was computed with 10 bootstrap samples.
#> 
#> # tibble [3 × 11]
#>   group1 group2 mean.difference conf.low conf.high    se t.value    df
#>   <chr>  <chr>            <dbl>    <dbl>     <dbl> <dbl>   <dbl> <dbl>
#> 1 R      PG-13           -0.219   -0.375    -0.064 0.047   3.31  1142.
#> 2 R      PG              -0.323   -0.573    -0.074 0.075   3.05   277.
#> 3 PG-13  PG              -0.104   -0.362     0.154 0.077   0.952  309.
#> # ... with 3 more variables: p.value <dbl>, significance <chr>,
#> #   p.value.label <chr>
#> Note: Shapiro-Wilk Normality Test for rating : p-value = < 0.001
#> 
#> Note: Bartlett's test for homogeneity of variances for factor mpaa : p-value = 0.004
#> 
```



<sup>Created on 2018-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by IndrajeetPatil** [comment]
Perfect! Everything looks good now. I will merge the PR once the Travis builds are completed. Thanks.

**Pull request merged**
