### PR TITLE
Rho as effect for Mann Whitney test

### PR DESCRIPTION
**Pull request by ibecav**
Still need to double back to WSR for within subjects designs

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Can you please also include the within-subjects implementation in the same PR? 

I don't want to remove existing functionality when there is nothing to replace it (since now the Mann-Whitney only covers between-subjects design). There is no hurry for this to be immediately incorporated.

**Comment by ibecav** [comment]
I know that you don't want to drop functionality but things aren't quite right now in the `subtitle_mann_nonparametric` function as it exists, and since we don't yet support within subjects at `ggbetweenstats`level just in the subtitle functions...

Easy example using your own df_bird from the test you built.  There's only 16 birds A-P but because you converted to long format it is reporting N=32.

Anyway I'm looking at it now.  the tricky part is supporting long and wide formats equally well.

**Comment by IndrajeetPatil** [comment]
Dang it! This easily fixable though. 

Just checked and this issue holds **only for the non-parametric** test.

``` r
library(ggstatsplot)


# made up data
Input <- (
  "
              Bird   Typical  Odd
              A     -0.255   -0.324
              B     -0.213   -0.185
              C     -0.190   -0.299
              D     -0.185   -0.144
              E     -0.045   -0.027
              F     -0.025   -0.039
              G     -0.015   -0.264
              H      0.003   -0.077
              I      0.015   -0.017
              J      0.020   -0.169
              K      0.023   -0.096
              L      0.040   -0.330
              M      0.040   -0.346
              N      0.050   -0.191
              O      0.055   -0.128
              P      0.058   -0.182
              "
)

# creating a dataframe
df_bird <- read.table(textConnection(Input), header = TRUE)

# converting to long format
df_bird %<>%
  tibble::as_tibble(x = .) %>%
  tidyr::gather(data = .,
                key = "type",
                value = "length",
                Typical:Odd)

# parametric
ggstatsplot::subtitle_t_parametric(
  data = df_bird,
  x = type,
  y = length,
  paired = TRUE
)
#> paste(NULL, italic("t"), "(", "15", ") = ", "-4.06", ", ", italic("p"), 
#>     " = ", "0.001", ", ", italic("g"), " = ", "0.96", ", CI"["95%"], 
#>     " [", "0.08", ", ", "1.96", "]", ", ", italic("n"), " = ", 
#>     16L)

# robust
ggstatsplot::subtitle_t_robust(
  data = df_bird,
  x = type,
  y = length,
  paired = TRUE
)
#> Note: 95% CI for effect size estimate was computed with 100 bootstrap samples.
#> 
#> paste(NULL, italic("t"), "(", "13", ") = ", "-3.84", ", ", italic("p"), 
#>     " = ", "0.002", ", ", italic(xi), " = ", "0.70", ", CI"["95%"], 
#>     " [", "0.39", ", ", "0.97", "]", ", ", italic("n"), " = ", 
#>     16L)

# bayes
ggstatsplot::subtitle_t_bayes(
  data = df_bird,
  x = type,
  y = length,
  paired = TRUE
)
#> paste(italic("t"), "(", 15, ") = ", "-4.06", ", log"["e"], "(BF"["10"], 
#>     ") = ", "3.6", ", ", italic("r")["Cauchy"], " = ", "0.707", 
#>     ", ", italic("d"), " = ", "-1.02", ", ", italic("n"), " = ", 
#>     16L)

# non-parametric
ggstatsplot::subtitle_mann_nonparametric(
  data = df_bird,
  x = type,
  y = length,
  paired = TRUE
)
#> paste(NULL, "log"["e"](italic("W")), " = ", "2.30", ", ", italic("p"), 
#>     " = ", "0.003", ", ", Delta["HLS"], " = ", "-0.13", ", CI"["95%"], 
#>     " [", "-0.21", ", ", "-0.05", "]", ", ", italic("n"), " = ", 
#>     32L)
```

Also, **all** functions in `ggstatsplot` expect the data to be in tidy/long format and not Cartesian format. So, you need not support both of these. I saw that you added support for both of them in `effsize_t_parametric` function, but I think it will be good to have a consistent API across functions.

**Comment by ibecav** [comment]
I totally disagree with not supporting wide format.  I realize it is sort of the tidy way but as a practionner it is horrible for data entry and with functions like wilcox test that are fussy...

**Comment by ibecav** [comment]
Okay I finished up the code for within subjects.  Accepts wide and long.  Fixed sample size and made changes to report V or W as needed.

BTW have I persuaded you to drop the log thing yet?

All tests pass and all examples work include mine up above

**Comment by IndrajeetPatil** [comment]
Thanks. All of this looks good to me. What is _V_ denoting for paired designs (like _W_ - Wilcoxon for between-subjects design)? 

Feel free to change the documentation. Given just how many different ways there seems to be to compute effect sizes here, I think it will be really helpful if you can include a detailed account of how these were computed in the `#' @details` field of the roxygen template. 

Let's come back to whether to log-transform the `statistic` value or not once this is merged.

**Comment by ibecav** [comment]
Go ahead and merge when it passes the tests. I'll do doco in the morning.  The answer to the V vs W question is the fact that we are now technically using two different tests which by convention use V & W


> wilcox.test(... , paired = FALSE, ...)

	Wilcoxon rank sum test with continuity correction a.k.a. Mann Whitney reports W

data:  wsrdata$grade_test1 and wsrdata$grade_test2
W = 163.5, p-value = 0.33
alternative hypothesis: true location shift is not equal to 0

> wilcox.test(..., paired = TRUE, ...)

	Wilcoxon signed rank test with continuity correction reports V

data:  wsrdata$grade_test1 and wsrdata$grade_test2
V = 2, p-value = 0.0001965
alternative hypothesis: true location shift is not equal to 0

but as you can see with the same data you get very different results much as you do if you choose paired-t versus independent.

**Pull request merged**
