### PR TITLE
Issue38 solution

### PR DESCRIPTION
**Pull request by ibecav**
Hi Indrajeet,

Well I'm embarrassed at how long this took me and how ugly the commit is but I think I fixed it!  Key was of course in the quoting, but there were several other errors along the way.  Reprex including.  Pardon the WORKING directory you can ignore it that's just where I put the reprex script to keep track

Chuck

``` r
library(tidyverse)

# for reproducibility
set.seed(123)

# first run the example from the base code
# creating dataframe
mtcars_new <- mtcars %>%
  tibble::rownames_to_column(., var = "car") %>%
  tibble::as_data_frame(x = .)

# simple function call with the defaults
ggstatsplot::ggscatterstats(
  data = mtcars_new,
  x = wt,
  y = mpg,
  type = "np",
  # have to quote car variable now
  label.var = "car",
  label.expression = "wt < 4 & mpg < 20",
  axes.range.restrict = TRUE,
  centrality.para = "median"
)
#> Note: 95% CI for Spearman's rho was computed with  100 bootstrap samples.
#> 
#> Coordinate system already present. Adding new coordinate system, which will replace the existing one.
#> Warning: The plot is not a `ggplot` object and therefore can't be further modified with `ggplot2` functions.
#> 
# works as advertised

# too many rows for debugging makes it slow.  Let's sample
movies_short <- ggstatsplot::movies_wide %>% group_by(mpaa) %>% sample_n(7) %>% ungroup
# str(movies_short)


# let's split the dataframe and create a list by mpaa rating
mpaa_list <- movies_short %>%
  base::split(x = ., f = .$mpaa, drop = TRUE)

# this created a list with 4 elements, one for each mpaa rating
# you can check the structure of the file for yourself
# str(mpaa_list)

# checking the length and names of each element
length(mpaa_list)
#> [1] 4
names(mpaa_list)
#> [1] "NC-17" "PG"    "PG-13" "R"

# running function on every element of this list note that if you want the same
# value for a given argument across all elements of the list, you need to
# specify it just once
plot_list1 <- purrr::pmap(
  .l = list(
    data = mpaa_list,
    x = "budget",
    y = "rating",
    xlab = "Budget (in millions of US dollars)",
    ylab = "Rating on IMDB",
    title = list(
      "MPAA Rating: NC-17",
      "MPAA Rating: PG",
      "MPAA Rating: PG-13",
      "MPAA Rating: R"
    ),
#    label.var = list("title", "year", "votes", "genre"),
# genre doesn't exist!
# Tried lots of permutations can only get it to work with some good old
# fashioned quotes
    label.var = list("title", "year", "votes", "length"),
    label.expression = list(
      ("rating > 6 & budget < 50"),
      ("rating > 6 & budget < 100"),
      ("rating > 6 & budget < 50"),
      ("rating > 6 & budget < 10")
    ),
    type = list("r", "np", "p", "np"),
    method = list(MASS::rlm, "lm", "lm", "lm"),
    marginal.type = list("histogram", "boxplot", "density", "violin"),
    centrality.para = "mean",
    xfill = list("#56B4E9", "#009E73", "#999999", "#0072B2"),
    yfill = list("#D55E00", "#CC79A7", "#F0E442", "#D55E00"),
    ggtheme = list(
      ggplot2::theme_grey(),
      ggplot2::theme_classic(),
      ggplot2::theme_light(),
      ggplot2::theme_minimal()
    ),
    messages = FALSE
  ),
  .f = ggstatsplot::ggscatterstats
)
plot_list1
```

    #> $`NC-17`
    #> 
    #> $PG
    #> 
    #> $`PG-13`
    #> 
    #> $R

<sup>Created on 2018-09-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
This is incredible! Thank you so much for all the detective work to have this resolved. This was a super-difficult bug for me to solve and I'm really glad you found a solution.

Can you please make the following changes to the PR and then I can merge this in the `master` branch:
1. Can you remove the new `WORKING` directory since it's not really useful?
2. You have a ton of commented code in `ggscatterstats.R`, which is a bit confusing and makes the code hard to read. Can you also get rid of those lines?
3. Can you **embed plots** in PR to show that all of the examples (with `label.var` and `label.expression`) are working as before: 

- [ ] `ggscatterstats` 
- [ ] `grouped_ggscatterstats` 
- [ ] `ggscatterstats` with `purrr` (but please used `ggstatsplot::combine_plots()` function to combine them into a single plot; currently they are laid on top of each other and I can't see any single plot)

Sorry for asking for so much, but I want to be absolutely sure that the behavior of the function hasn't changed with the new changes. Pretty sure it hasn't, but doesn't hurt to check 💯

**Comment by ibecav** [comment]
Hi,

Glad to be helpful.  Currently rebuilding and rechecking the code which is helping me identify a bunch of little dependencies.  Unfortunately building your vignettes takes forever as you know :-( ...

To your specifics:

1.  I'll try and .gitignore the WORKING directory but I can't function without it.  I'll also see if I can figure out how to do a pull request but not include some files like that one.

2.  I'll get rid of a bunch of them.

3.  I have no clue how to embed the graphs I just used reprex() with the rscrpit on the clipboard.  What do I need to do differently?

4.  I also am fixing the doco will generate some new ".Rd" files

Please work on making those vignettes smaller.  This check and build lag is killing me.

Chuck

**Comment by IndrajeetPatil** [comment]
Yeah, really sorry about that. As you must have noticed, there are not a lot of unit tests yet and the way I was increasing code coverage was by making sure all parts of the function were getting used in `vignettes`. As a result, the vignettes are pretty long. I do plan to reduce them because the size of the package is exceeding `5 MB` and the `CRAN` checks also take longer than 10 minutes, none of which will be acceptable.

How are you creating a `reprex`? Are you using RStudio add-in (which comes with `reprex` package).

Here is how use it.

Step-1: select the code you want to use and choose to render `reprex`

image

Step-2: and then choose the appropriate options and it will save the `reprex` to clipboard which you can post to GitHub

image

**Comment by ibecav** [comment]
ggscatterstats reprex

``` r
library(tidyverse)

# for reproducibility
set.seed(123)

# first run the example from the base code
# creating dataframe
mtcars_new <- mtcars %>%
  tibble::rownames_to_column(., var = "car") %>%
  tibble::as_data_frame(x = .)

# simple function call with the defaults
ggstatsplot::ggscatterstats(
  data = mtcars_new,
  x = wt,
  y = mpg,
  type = "np",
  # have to quote car variable now
  label.var = "car",
  label.expression = "wt < 4 & mpg < 20",
  axes.range.restrict = TRUE,
  centrality.para = "median"
)
#> Note: 95% CI for Spearman's rho was computed with  100 bootstrap samples.
#> 
#> Coordinate system already present. Adding new coordinate system, which will replace the existing one.
#> Warning: The plot is not a `ggplot` object and therefore can't be further modified with `ggplot2` functions.
#> 
```



``` r
# works as advertised
```

<sup>Created on 2018-09-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ibecav** [comment]
grouped_ggscatterstats reprex

``` r
# to ensure reproducibility
set.seed(123)

# basic function call
ggstatsplot::grouped_ggscatterstats(
  data = dplyr::filter(
    ggstatsplot::movies_long,
    genre == "Comedy" |
      genre == "Drama"
  ),
  x = length,
  y = rating,
  method = "lm",
  formula = y ~ x + I(x^3),
  grouping.var = genre
)
#> Warning: The plot is not a `ggplot` object and therefore can't be further modified with `ggplot2` functions.
#> 
#> Warning: The plot is not a `ggplot` object and therefore can't be further modified with `ggplot2` functions.
#> 
#> Warning: The output from `grouped_` functions are not `ggplot` objects and therefore can't be further modified with `ggplot2` functions.
#> 
```



``` r

# using labeling
ggstatsplot::grouped_ggscatterstats(
  data = dplyr::filter(ggplot2::mpg, cyl != 5),
  x = displ,
  y = hwy,
  grouping.var = cyl,
  title.prefix = "Cylinder count",
  type = "robust",
  label.var = "manufacturer",
  label.expression = "hwy > 25 & displ > 2.5",
  messages = FALSE
)
```



``` r

# labeling without expression
ggstatsplot::grouped_ggscatterstats(
  data = dplyr::filter(
    .data = ggstatsplot::movies_long,
    rating == 8,
    genre %in% c("Drama", "Comedy")
  ),
  x = budget,
  y = length,
  grouping.var = genre,
  label.var = "title",
  results.subtitle = FALSE,
  marginal = FALSE,
  title.prefix = "Genre",
  caption.text = "All movies have IMDB rating greater than 8."
)
#> Warning: The output from `grouped_` functions are not `ggplot` objects and therefore can't be further modified with `ggplot2` functions.
#> 
```



<sup>Created on 2018-09-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by IndrajeetPatil** [comment]
Hmm, there is a merge conflict now. I can take care of changing the vignettes, so no need to change those files.

**Pull request merged**
