### PR TITLE
Datafix for movies_long

### PR DESCRIPTION
**Pull request by ibecav**
As currently configured movies_long is an odd hybrid between repeated measures and indepent.  This change gives you a movies_long dataset where all the genre categories are orthogonal and you can compare those categories fairly.  Nothing changes in movies_wide and the column names in movies_long remain the same.

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Hmm, I don't think it's a good idea to call this new dataset `movies_long`. Changing `movies_long` now is going to break a lot of tests and will also break backward compatibility. None of the tests are failing for your PR because you have changed the raw code to create data but haven't actually created the new dataset using this code. If you do that, the tests should fail.

Can you create a separate file in the `data-raw` folder called `movies_tidy.R` and then **generate** a new dataset called `movies_tidy`? Please also make sure to add documentation for this new dataset in the `data.R` file in `R` folder.

**Comment by ibecav** [comment]
Yes I realize that making changes to movies_long has quite a few downstream effects.  But they are mainly in tests.  One way or another you're going to want to move away from the current version of movies_long so adding a 3rd dataset called movies_tidy just delays that.

I was thinking just "bite the bullet" and make the changes all at once. I have generated thsi new version locally on my machine and can see the places where tests need to be changed.

**Comment by ibecav** [comment]
All tests  work again.  I'll go through the rmd files as well
══ Results ════════════════════════════════════════════════════════════════════════════════════════════
Duration: 118.9 s

OK:       685
Failed:   0
Warnings: 0
Skipped:  0

**Comment by IndrajeetPatil** [comment]
Okay. Please also make sure to change the description of the data in the `data.R` file-
https://github.com/IndrajeetPatil/ggstatsplot/blob/7a06f82a10f6eb364806af501f28a9b23ff26217/R/data.R#L36-L69

**Comment by ibecav** [comment]
Just did, next step I'll double check all the Rmd files

**Comment by IndrajeetPatil** [comment]
Also, `README.Rmd` file contains a number of instances of this dataset that will probably need to be fixed.

**Comment by ibecav** [comment]
Yes I visited the README as well.  I'll go over the Rmd vignettes some more but everything is functional and passes tests.  If you want to review this PR I can do more tomorrow.

**Pull request merged**
