### PR TITLE
adding Bayes T test test

### PR DESCRIPTION
**Pull request by ibecav**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Thanks. 

Can you also add another test with `paired = TRUE` to check if this function is also working correctly for within-subjects designs? 

There is a new dataset `iris_long` in `ggstatsplot`, which is in tidy data format and suitable for testing within-subjects designs.

**Comment by IndrajeetPatil** [comment]
Saw the separate PR. Thanks!

**Comment by ibecav** [comment]
Yes I did both of these paired and unpaired.  Enjoy your thankgiving I'm done for the week.

**Comment by IndrajeetPatil** [comment]
Happy Thanksgiving to you too, Chuck! Enjoy the holidays.

**Pull request merged**
