### PR TITLE
Don't accept this yet!

### PR DESCRIPTION
**Pull request by ibecav**
But do please look it over for where I'm heading and some inconsistencies in the current doco.

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
I like the changes you have made to the **Introduction** section, but I would prefer if the current examples are retained. 

I am not sure why you want to change the `lm` example from an interesting movies dataset to `mtcars`, which is as boring as the datasets go.
This is incorrect, btw: `ggplot2::labs(x = "effect size estimate (partial omega-squared)"` since regression estimates are being displayed here, not partial omega-squared. 
Also, in my view, `title` for the plot should reveal what the plot is overall about (which is what the exisiting `lm` example is doing), but the plot `title` you are using is rather redundant and uninformative.

**Comment by IndrajeetPatil** [comment]
Also, you'll see that the results from `lmer` here is incorrect because the p-value is > 0.05 and 95% CI still doesn't contain 0. This is not a bug in `ggstatsplot`, but a bug in `broom.mixed` (https://github.com/bbolker/broom.mixed/issues/30) which has now been fixed.

image

**Comment by IndrajeetPatil** [comment]
1. I am not sure what the inconsistency is here: `effsize` and `nboot` arguments are relevant only for models objects of class `aov`, `anova`, and `aovlist`. It's not going to change anything for `lm` objects. There are a lot of model-specific arguments in this functions, e.g., `se.type` or `coefficient.type` won't change a thing for `lm` objects either.

2. I'd love to add details like adjusted R squared, but they are not available for all regression models. As the first draft of this function, I wanted to include details that **all** regression models will contain (`tidy::glance`), which happen to be AIC, BIC, and LL. In future, I do plan to make more fine-grained captions though that show different details based on different models.

**Comment by ibecav** [comment]
I'm not picking on anything or complaining.  Just noting inconsistencies that appear to me as a first time user  of this function. If the arguments only apply in some cases we should probably make that clear at least at `?ggcoefstats`.  It's one of the challenges with a function that tries to do a lot of different things.  I'll keep sending drafts.  I'm not hardset on any of my suggestions just trying to make it clearest for the largest possible audience.

**Comment by IndrajeetPatil** [comment]
Gotcha. I've started working on `ggcoefstats` roxygen documentation to address this concern. I'll specify for every class-specific argument, which class it is relevant for.

**Comment by IndrajeetPatil** [comment]
Hmm, if we are going to introduce standardizing regression coefficients, why not just use this existing function (https://github.com/fsolt/dotwhisker/blob/master/R/by_2sd.R)? 
That way, we can standardize the regression coefficient, irrespective of whether the model object is `"lm"`, `"lmer"`, `"glmer"`, `"nlmer"`, etc. 

I want to maintain the generality of this function and standardizing regression coefficient only for `"lm"` just narrows its scope.

**Comment by ibecav** [comment]
You can apply this method which is quite common and mentioned [here](https://stats.stackexchange.com/questions/269452/formula-for-standardized-regression-coefficientsderivation-and-intuition) and supported by lm.beta to any number of methods as well.  I would just like to get some form of standardized coeffs because non-standardized ones don't graph well often.

``` r
library(ggstatsplot)
ours<- ggstatsplot::ggcoefstats(
      x = stats::lm(
      formula = rating ~ budget * length,
      data = movies_long
      ),
      conf.level = 0.99,
      output = "tidy")
theirs <- lm.beta::lm.beta(lm(
  formula = rating ~ budget * length,
  data = movies_long
))
theirs$standardized.coefficients
#>   (Intercept)        budget        length budget:length 
#>    0.00000000    0.08602724    0.49745967   -0.23182175
ours$std.coef
#> [1]  0.08602724  0.49745967 -0.23182175
```

<sup>Created on 2018-10-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by IndrajeetPatil** [comment]
What about `lmer`, `clm`, `clmm`, etc. models? Will it also standardize those regression coefficients?

**Comment by IndrajeetPatil** [comment]
(Also, the Travis build is failing for your branch, so `ggcoefstats` is not working properly.)

**Comment by ibecav** [comment]
Right not looking for a merge yet so I haven't been tracking closely although I doubt I have done anything to break the build.

As to work elsewhere Gelman is advocated twice the standard deviation of x where as this formula is 

ylqk9

Mathmatically the only bad case would be if your outcome had a standard deviation of zero in which case you got lots of problems.  But yes I'm recommending we take it slow and I'll test the others.

**Comment by IndrajeetPatil** [comment]
Okay, in that case, can you please separate these changes into two separate PRs:
- one dedicated **solely** to the changes in `ggcoefstats` vignette, which will be straightforward to accept
- experimental branch for standardizing regression coefficients, which will take a much longer time to think about and implement

**Comment by ibecav** [comment]
Agreed I was thinking ahead and wound up in one branch I’ll fix tomorrow

**Comment by ibecav** [comment]
I'm going to close this pull request and move the discussion to the issue you created.

**Pull request closed without merging**
