### PR TITLE
Cramer v

### PR DESCRIPTION
**Pull request by ibecav**
Sorry somehow there are discrepanices in unrelated files I can't get github to fix this includes function doco and tests

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Thanks, Chuck! 

The discrepancies are stemming from the fact that I am working with the development version of `ggplot2`, while you have the `CRAN` version. So some of the `#' @importFrom` roxygen documentation that links to `ggplot2` generates different documentation.

**Comment by ibecav** [comment]
Okay I think it’s all good builds and tests fine on mine

**Comment by IndrajeetPatil** [comment]
Okay, so a few changes to make before all the checks pass and I merge this:

- [ ] Update to the development version of `ggplot2` and regenerate the roxygen documentation (this should remove the changes to `.Rd` files)
- [ ] Clean lints by using `styler` on the `.R` file that contains the new function
- [ ] Add tests to cover the following lines of code which are currently missing coverage

image

**Comment by IndrajeetPatil** [comment]
Awesome. I will take care of the docs and also use this new function in the appropriate contexts and update the tests. 

Thanks a ton, again, for adding this new function!!

Will merge once the checks are completed.

**Comment by IndrajeetPatil** [comment]
The builds are succeeding. On Travis, the builds stall while running tests with the following message-

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

I think this has something to do with what you had said-

> The tests can be quite expensive in NCP when you start pushing the upper and lower boundaries. 

So two things:
1. Is there any way to replace this test with something less computationally expensive without reducing code coverage? Because, otherwise, our Travis builds will never succeed.

```r
    res3 <- ggstatsplot:::cramer_v_ci(table(Titanic_full$Sex),
      conf.level = .99,
      method = "ncchisq",
      p = c(.2135, .7865)
    )
```

2. Can you import the following function: `stats::pchisq`?
You are relying on it heavily but not importing it, which is producing a `NOTE` in `R CMD CHECK`.

**Comment by ibecav** [comment]
Sorry I’m slow at a conference 

You are correct that was totally my point pushing the boundaries of the upper and lower limits of the cis is very computationally intensive. Terrible in Travis bad enough even locally. Sadly not resolvable by choosing a smaller N. Recommend just dropping them I have tested them locally they work. The code coverage drop is quite small actually and we know the issue

I will add that dependency when I can

Recommend

**Pull request merged**
