### PR TITLE
Test robcor_ci in helpers_effsize_ci

### PR DESCRIPTION
**Pull request by ibecav**
Substantially the same as test_cor_tets_ci

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
In `context("lm_effsize_ci")`, can you include instances of all types of objects that `lm_effsize_ci` works with?

```
object: The linear model object (can be of class lm, aov, anova, or aovlist).
```

Currently, only class `lm` is being tested.

**Comment by ibecav** [comment]
Happy to on some future date likely next week. I’m about bored with test scripts for the rest of this week. 

Up to you whether you want to commit as is or wait.

**Comment by ibecav** [comment]
Oh forgot to ask I notice “code coverage” isn’t going up any of at all at least in the messages I get back. I thought we were doing this to increase that concept?

**Comment by IndrajeetPatil** [comment]
Okay, I will merge these PRs tonight and then you can work some other time on the tests for the `lm_effsize_ci` function.

The code coverage _is_ going up. You can track it here (I will update this document after every new test):
https://github.com/IndrajeetPatil/ggstatsplot/blob/master/tests/README.md

You don't see the difference in code coverage on PRs themselves because it is also using the `vignettes` to compute the code coverage, while `covrpage` uses only `tests`. Ultimately, when we have enough tests, I will change this code to just use tests to compute code coverage-
https://github.com/IndrajeetPatil/ggstatsplot/blob/767aedc2931a3f3b8dcbe203e931111b7eb5b602/.travis.yml#L74

**Comment by ibecav** [comment]
Thanks that helps my understanding.  Not to minimize the value of automated
testing but I'd also argue the code is in need of some user error trapping
and friendlier warning and error messages.

**Comment by ibecav** [comment]
I tried to do this.  Succeeded for lm, aov, and aovlist.  Submitted PR.
There's a bug in lm_effsize_ci that needs correcting before I can add the
test successfully.  Submitted reprex

**Pull request merged**
