### PR TITLE
Aligning Spearman effect size #162

### PR DESCRIPTION
**Pull request by ibecav**
regardless of whether we started long or wide removing artifact

#162

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Tests are failing.

**Comment by ibecav** [comment]
Well one test was actually failing because of the change I made now reporting the right value.  While I was at it I suppressed the annoying failed to converge warning I had told you about previously.

Man there's a lot of trash in the test output.

Any plans to fix the two that fail in coefstats?

PR updated

**Comment by IndrajeetPatil** [comment]
Okay, few things-
1. It's not "trash". Those messages are deliberately being printed because the lines of code corresponding to those messages need to be covered.
2. Those tests are failing on your local machine because they work only with the development versions of `broom` and `broom.mixed`. You can pay no attention to them, they are skipped on `CRAN`, `AppVeyor`, and `Travis` for that very same reason. (This is also the reason when you do `devtools::document()`, you get a change `.Rd` file for `ggcoefstats`).

**Comment by ibecav** [comment]
Didn't mean to be cranky about the testing output, just makes it hard to find the wheat (true problems) in the chaff (warnngs and other messages).

**Comment by IndrajeetPatil** [comment]
The problem is that for plotting functions I don't how to `capture.output` (which will extract the message being displayed) while suppressing the graphic output. That will make testing messages easier.

**Pull request merged**
