### PR TITLE
This repo should be considered as R code

### PR DESCRIPTION
**Pull request by hbaniecki**
Should cover this `HTML` contribution and list this repo as `R` on GitHub. May update after the next commit to master branch though.
image

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Thanks :)

**Comment by IndrajeetPatil** [comment]
@hbaniecki Any ideas on why the repo might still be being tagged as HTML even after a recent commit to the master?

**Comment by hbaniecki** [comment]
Weird case. The syntax is pretty straightforward [linguist>documantation](https://github.com/github/linguist#documentation) and it worked for me on several repositories.  Maybe it just lagged as [explained here](https://github.com/github/linguist#how-linguist-works-on-githubcom), and will work soon. In a while you could try:
- `docs/** linguist-documentation`
- `*.html linguist-documentation`

**Comment by hbaniecki** [comment]
@IndrajeetPatil In addition, there is a possibility to remove the `docs` folder from `master` branch and have it entirely on `gh-pages` branch. The whole process can be automated with GitHub Actions. Every push to `master` initializes the job that builds the `pkgdown` site for you and then pushes it to `gh-pages` branch. It's not hard to achieve. e.g. 
https://github.com/ModelOriented/modelStudio
https://github.com/ModelOriented/modelStudio/tree/gh-pages

**Pull request merged**
