### PR TITLE
Remove `plot.type` argument for `ggbetweenstats()`

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
- Bump to devel
- Closes [#849](https://github.com/IndrajeetPatil/ggstatsplot/issues/849)
- Closes [#670](https://github.com/IndrajeetPatil/ggstatsplot/issues/670)
- Adjust docs and tests for the same

### CODE REVIEW

**Comment by qqwxp** [comment]
why remove it? Are there any alternative methods to get a boxplot?

**Comment by IndrajeetPatil** [comment]
> why remove it? Are there any alternative methods to get a boxplot?

I have removed it because it was redundant.

Yes there is. Have a look at [this](https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/ggbetweenstats.html#comparisons-between-groups-with-ggbetweenstats) vignette, which shows how to get a boxplot, violin plot, etc.

image

**Comment by AntoineSoetewey** [comment]
Dear @IndrajeetPatil,

I believe using `violin.args = list(width = 0)` to remove the violin plot is not ideal when there is at least one outlier.

For instance, we see that there is an outlier in the post-test:

Screenshot 2023-10-16 at 19 07 27

When removing the violin plot with `violin.args = list(width = 0)`, we don't see that the observation is an outlier anymore (+ there is a vertical line inside the boxplot, which is uncommon):

Screenshot 2023-10-16 at 19 08 37

By any chance, is there another way to just have a boxplot without the violin plot?

Regards,
Antoine

**Comment by AntoineSoetewey** [comment]
Dear @IndrajeetPatil,

Do you have any thoughts following my previous message?

Thanks in advance!

**Comment by IndrajeetPatil** [comment]
I believe the fact that the box plot whiskers go up until the outlier point is a bug in ggstatsplot: https://github.com/IndrajeetPatil/ggstatsplot/issues/895

Once that's fixed, this shouldn't be an issue anymore.

**Pull request merged**
