### PR TITLE
Bug fix #105

### LINKED ISSUE #105: making `ggscatterstats` consistent with the overall API
Since #38 was solved, `ggscatterstats` arguments `label.var` and `label.expression` work only with characters but not bare expressions. This is incosistent with the API principles for the rest of the functions in the package. It will be nice if this function's arguments behaved the same way as other functions and accepted both bare expressions and characters.

``` r
# setup
set.seed(123)
library(ggstatsplot)
library(ggplot2)

# works
ggscatterstats(
  msleep,
  brainwt,
  sleep_total,
  marginal = FALSE,
  label.var = "genus",
  label.expression = "brainwt > 3"
)
```

``` r

# doesn't work
ggscatterstats(
  msleep,
  brainwt,
  sleep_total,
  marginal = FALSE,
  label.var = genus,
  label.expression = brainwt > 3
)
#> Error in parse_exprs(x): object 'brainwt' not found
```

<sup>Created on 2018-12-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### PR DESCRIPTION
**Pull request by ibecav**
Man these are painful.  Trying to account for all the options and get the quotation and quasi-quotation right may be unsustainable for the long haul.  Might be easier to force some user discipline.

Here's the PR had to change code in two different locations.  And the solutions are different.  `label.expression` is tough because there's a lot you can pass in a language call.  The `label.var` is more or less because of limits in `ggrepel` 

Reprex below.  If this is good I think some simple changes are needed in the  doco.

``` r
#### bug #105
library(ggstatsplot)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2)
# test all four combinations
# no quotes
ggscatterstats(
  msleep,
  brainwt,
  sleep_total,
  marginal = FALSE,
  label.var = genus,
  label.expression = brainwt > 3
)
```

``` r
# both quotes
ggscatterstats(
  msleep,
  brainwt,
  sleep_total,
  marginal = FALSE,
  label.var = "genus",
  label.expression = "brainwt > 3"
)
```

``` r
# just label.var
ggscatterstats(
  msleep,
  brainwt,
  sleep_total,
  marginal = FALSE,
  label.var = "genus",
  label.expression = brainwt > 3
)
```

``` r
# just label.var
ggscatterstats(
  msleep,
  brainwt,
  sleep_total,
  marginal = FALSE,
  label.var = genus,
  label.expression = "brainwt > 3"
)
#trickier a complex expression
# to get reproducible results from bootstrapping
set.seed(123)

# creating dataframe
mtcars_new <- mtcars %>%
  tibble::rownames_to_column(., var = "car") %>%
  tibble::as_tibble(x = .)

ggstatsplot::ggscatterstats(
  data = mtcars_new,
  x = wt,
  y = mpg,
  type = "np",
  label.var = "car",
  label.expression = wt < 4 & mpg < 20,
  axes.range.restrict = TRUE,
  centrality.para = "median",
  xfill = NULL
)
#> Note: 95% CI for effect size estimate was computed with 100 bootstrap samples.
#> 
#> Coordinate system already present. Adding new coordinate system, which will replace the existing one.
#> Warning: This plot can't be further modified with `ggplot2` functions.
#> In case you want a `ggplot` object, set `marginal = FALSE`.
#> 
```

<sup>Created on 2018-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### CODE REVIEW

**Comment by ibecav** [comment]
Think I'm done with grouped as well.

``` r
#### bug #105 continued
library(ggstatsplot)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2)
# no quotes
ggstatsplot::grouped_ggscatterstats(
   data = dplyr::filter(ggplot2::mpg, cyl != 5),
   x = displ,
   y = hwy,
   grouping.var = cyl,
   title.prefix = "Cylinder count",
   type = "robust",
   label.var = manufacturer,
   label.expression = hwy > 25 & displ > 2.5,
   xfill = NULL,
   package = "yarrr",
   palette = "appletv",
   messages = FALSE
 )
```



``` r
# both quotes
ggstatsplot::grouped_ggscatterstats(
  data = dplyr::filter(ggplot2::mpg, cyl != 5),
  x = displ,
  y = hwy,
  grouping.var = cyl,
  title.prefix = "Cylinder count",
  type = "robust",
  label.var = "manufacturer",
  label.expression = "hwy > 25 & displ > 2.5",
  xfill = NULL,
  package = "yarrr",
  palette = "appletv",
  messages = FALSE
)
```



<sup>Created on 2018-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ibecav** [comment]
When you're good with these I'll take a look at tests and doco although I'm pretty sure we're there.

**Comment by IndrajeetPatil** [comment]
This is beautiful, Chuck! So happy to see that you got this to work. 

The lints can be ignored for now.

The only thing to change now is to modify the tests to account for this new behavior. Can you please change `test_ggscatterstats.R` and `test_grouped_ggscatterstats.R` to check all four combinations of `label.var` and `label.expression` are encountered in these tests? 
This way the code coverage check won't fail.

**Comment by ibecav** [comment]
Thanks I can do it Weds just have to Xmas shop tomorrow or I’m in deep trouble

**Pull request merged**
