### PR TITLE
Refactor grouped_ggcorrmat

### PR DESCRIPTION
**Pull request by ibecav**
Well that was a bit of a struggle and I had to go a different way. No changes to tests or doco.

Don't know if you did it deliberately but the original line 136-140 didn't do much the end result was select everything.  Turns out the easiest thing to do was simply make it unnecessary to pass `cor.vars` through `purrr` at all.  Turns out that is hard to do.  So I make the grouped_ version do the work of reducing the dataframe and nesting it and then I don't have to pass it.

Should be good.  Turns out the non-grouped version accepts numerics 6:10 but the grouped_ version didn't before and won't now.  As the reprex shows all the other reasonable permutations work.  

``` r
library(ggplot2)
library(ggstatsplot)
# for reproducibility
set.seed(123)
ggstatsplot::grouped_ggcorrmat(
  data = ggplot2::msleep,
  grouping.var = vore
)
#> Warning: Individual plots in the combined `grouped_` plot
#> can't be further modified with `ggplot2` functions.
#> 
```

``` r

# for getting confidence intervals
# confidence intervals are not available for **robust** correlation
ggstatsplot::grouped_ggcorrmat(
  data = datasets::iris,
  grouping.var = Species,
  p.adjust.method = "holm",
  cor.vars = c("Sepal.Length", "Petal.Width"),
  output = "ci"
)
#> Note: In the correlation matrix,
#> the upper triangle: p-values adjusted for multiple comparisons
#> the lower triangle: unadjusted p-values.
#> 
#> Note: In the correlation matrix,
#> the upper triangle: p-values adjusted for multiple comparisons
#> the lower triangle: unadjusted p-values.
#> 
#> Note: In the correlation matrix,
#> the upper triangle: p-values adjusted for multiple comparisons
#> the lower triangle: unadjusted p-values.
#> 
#> # A tibble: 3 x 8
#>   Group      pair            r     lower upper        p lower.adj upper.adj
#>   <chr>      <chr>       <dbl>     <dbl> <dbl>    <dbl>     <dbl>     <dbl>
#> 1 setosa     Spl.L-Ptl.W 0.278 -0.000270 0.516  5.05e-2 -0.000270     0.516
#> 2 versicolor Spl.L-Ptl.W 0.546  0.316    0.716  4.04e-5  0.316        0.716
#> 3 virginica  Spl.L-Ptl.W 0.281  0.00299  0.519  4.80e-2  0.00299      0.519

ggstatsplot::grouped_ggcorrmat(
  data = datasets::iris,
  grouping.var = Species,
  p.adjust.method = "holm",
  cor.vars = "Sepal.Length":"Petal.Width"
)
#> Note: In the correlation matrix,
#> the upper triangle: p-values adjusted for multiple comparisons
#> the lower triangle: unadjusted p-values.
#> 
#> Note: In the correlation matrix,
#> the upper triangle: p-values adjusted for multiple comparisons
#> the lower triangle: unadjusted p-values.
#> 
#> Note: In the correlation matrix,
#> the upper triangle: p-values adjusted for multiple comparisons
#> the lower triangle: unadjusted p-values.
#> 
#> Warning: Individual plots in the combined `grouped_` plot
#> can't be further modified with `ggplot2` functions.
#> 
```

``` r

ggstatsplot::grouped_ggcorrmat(
  data = datasets::iris,
  grouping.var = Species,
  p.adjust.method = "holm",
  cor.vars = Sepal.Length:Petal.Width
)
#> Note: In the correlation matrix,
#> the upper triangle: p-values adjusted for multiple comparisons
#> the lower triangle: unadjusted p-values.
#> 
#> Note: In the correlation matrix,
#> the upper triangle: p-values adjusted for multiple comparisons
#> the lower triangle: unadjusted p-values.
#> 
#> Note: In the correlation matrix,
#> the upper triangle: p-values adjusted for multiple comparisons
#> the lower triangle: unadjusted p-values.
#> 
#> Warning: Individual plots in the combined `grouped_` plot
#> can't be further modified with `ggplot2` functions.
#> 
```

``` r

ggstatsplot::ggcorrmat(
data = ggplot2::msleep,
cor.vars = 6:10,
p.adjust.method = "BH",
output = "ci"
)
#> Note: In the correlation matrix,
#> the upper triangle: p-values adjusted for multiple comparisons
#> the lower triangle: unadjusted p-values.
#> 
#> # A tibble: 10 x 7
#>    pair             r  lower   upper         p lower.adj upper.adj
#>    <chr>        <dbl>  <dbl>   <dbl>     <dbl>     <dbl>     <dbl>
#>  1 slp_t-slp_r  0.752  0.617  0.844  2.92e- 12   0.543     0.873  
#>  2 slp_t-slp_c -0.474 -0.706 -0.150  6.17e-  3  -0.776     0.00641
#>  3 slp_t-awake -1.000 -1.000 -1.000  2.42e-226  -1.000    -1.000  
#>  4 slp_t-brnwt -0.360 -0.569 -0.108  6.35e-  3  -0.643     0.00813
#>  5 slp_r-slp_c -0.338 -0.614  0.0120 5.84e-  2  -0.703     0.168  
#>  6 slp_r-awake -0.752 -0.844 -0.617  2.91e- 12  -0.873    -0.543  
#>  7 slp_r-brnwt -0.221 -0.476  0.0670 1.31e-  1  -0.567     0.191  
#>  8 slp_c-awake  0.474  0.150  0.706  6.17e-  3  -0.00641   0.776  
#>  9 slp_c-brnwt  0.852  0.709  0.927  2.42e-  9   0.618     0.947  
#> 10 awake-brnwt  0.360  0.108  0.569  6.35e-  3  -0.00813   0.643

ggstatsplot::grouped_ggcorrmat(
  data = datasets::iris,
  grouping.var = Species,
  p.adjust.method = "holm",
  cor.vars = 6:10,
  output = "ci"
)
#> Error in inds_combine(.vars, ind_list): Position must be between 0 and n
```

<sup>Created on 2019-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Thanks, this all looks good. Even I didn't know that I could enter numbers that would be evaluated as column positions! I am absolutely fine if that doesn't work with any of the functions in this package as I find the practice of using numeric to specify columns to be really fragile.

The `grouped_ggcorrmat` function actually used the `purrr` hack twice; once for the plot and the other one for the tidy dataframe (`statsdf_purrr`). Do you also want to include that in the same PR? I can also take care of it, if you want. Seems like the same solution used for the plot part would apply for the stats part.
https://github.com/IndrajeetPatil/ggstatsplot/blob/e387a8524a7c832b7000e77f92bcebd0bce03045/R/grouped_ggcorrmat.R#L299-L353

**Comment by IndrajeetPatil** [comment]
Don't want to keep this waiting. Will be easier to just make a separate PR for the stats part.

**Comment by ibecav** [comment]
Okay I’ll look Monday

**Comment by ibecav** [comment]
Second part is refactored.  Same technique, simply delete the conditional logic and only pass ggcorrmat what it needs.  PR follows

**Pull request merged**
