### PR TITLE
adding bayes factor for goodness of fit test for proportions

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
Something is wrong with this implementation. No matter whether _p_ less than or greater than `0.05`, the Bayes Factor shows evidence always in favor of the null hypothesis. 

``` r
library(ggplot2)

# p > 0.05
ggstatsplot::ggpiestats(mtcars, am)
```

``` r

# p > 0.05
ggstatsplot::ggpiestats(mtcars, cyl)
```

``` r

# p < 0.001
ggstatsplot::ggpiestats(msleep, vore)
```

<sup>Created on 2019-06-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
@ibecav Do you know what I am doing wrong here?

I have got a hunch that this is the source of the issue, although I am not sure how else to implement a proportion test here.

https://github.com/IndrajeetPatil/ggstatsplot/blob/2ea379bfea438ec246e27027fb471e953151ad7c/R/helpers_bf_tests.R#L440-L450

**Comment by ibecav** [comment]
Indrajeet,

I saw you were in touch with Richard M.  I had also been looking at this
and until the most recent release of JASP couldn't find anyone who had
implemented the Bayesian equivalent of a Chi Sq GoF test or Bayesian
multinomial test.

I was able to peek under the covers in Jasp (
https://github.com/jasp-stats/jasp-desktop/blob/48ad5a41160ae39faaa43ef7606eea5aaecdebaa/JASP-Engine/JASP/R/multinomialtestbayesian.R)
and extract the key computational sub function from the code )most of which
is setup and plotting).  I have no idea how "correct" it is but it is
certainly easy enough to execute...

xxx <- function(alphas, counts, thetas) {

  # if needed: rescale
  if(sum(thetas) != 1) {
    thetas <- thetas/sum(thetas)
  }

  # expected counts under the null hypothesis (Binomial median)
  expected <- setNames(sum(counts)*thetas, names(counts))

  # compute Bayes factor
  lbeta.xa <- sum(lgamma(alphas + counts)) - lgamma(sum(alphas + counts))
  lbeta.a  <- sum(lgamma(alphas)) - lgamma(sum(alphas))

#  return(lbeta.a)

  # in this case, counts*log(thetas) should be zero, omit to avoid
numerical issue with log(0)
  if (any(rowSums(cbind(thetas, counts)) == 0)) {
    LogBF10 <- (lbeta.xa-lbeta.a)
  } else {
    LogBF10 <- (lbeta.xa-lbeta.a) + (0 - sum(counts * log(thetas)))
  }

  BF <- data.frame(LogBF10 = LogBF10,
                   BF10    = exp(LogBF10),
                   BF01    = 1/exp(LogBF10))

  return(list(BF       = BF,
              expected = expected))
}

this xxx function will return the same answers as they are delivering in
Jasp e.g.

xxx(alphas = c(1, 1, 1), counts = c(15, 12, 5), thetas = c(1,1,1))

is the same as doing a multinomial test on mtcars$gear (counts 15, 12, 5)
no prior information so alpha's are 1,1,1, and assuming equal expectations
in theta 1, 1, 1

It ertainly seems to give sensical answers until BayesFactor decides to
implement or not.

**Comment by IndrajeetPatil** [comment]
Hi Chuck,

Thanks a lot for digging into this. The current implementation of Bayesian goodness of fit test for a one-way table is based on what Richard had posted here:
https://gist.github.com/richarddmorey/a4cd3a2051f373db917550d67131dba4

The results are slightly different between Richard's code and JASP, but this is to be expected for reasons explained by Richard in this Twitter discussion I had with him: https://twitter.com/patilindrajeets/status/1050247725705510913

That said, if you think the JASP implementation makes more sense, I am willing to reconsider the current implementation since this is still not on CRAN and so no concerns about backward compatibility.

**Comment by IndrajeetPatil** [comment]
Sorry, had posted a link to the wrong Twitter thread. Edited to point to the correct one.

**Comment by ibecav** [comment]
I can't see anything in the twitter feed about why.  All I see is Richard's answer pointing back to the contingencytableBF doco

**Comment by IndrajeetPatil** [comment]
Gah, Twitter has made it impossible to read through threads. 

Here is the important part of the conversation:

1.
image

2. 
image

3.
image

4.
image

**Comment by ibecav** [comment]
LOL not a big fan of Twitter.  Haven't used an account in 5 years.

Got it. More in a minute

**Comment by ibecav** [comment]
Reprex follows:  Assuming that your prior alphas are of the form k = k = k then they produce identical answers (well near identical since Richard is simulating the data).  If the k's are not equal then JASP and BayesFactor produce different results even though they sum to the same number (Richard only uses the sum).  The Jasp module is about 3x faster (no MCMC) and reproducible (same answer every time).

For the reprex I tried to normalize the code between the tw0 as much as possible

``` r
jaspversion <- function(alphas, counts, thetas) {
  
  # if needed: rescale
  if(sum(thetas) != 1) {
    thetas <- thetas/sum(thetas)
  }
  
  # expected counts under the null hypothesis (Binomial median)
  expected <- setNames(sum(counts)*thetas, names(counts))
  
  # compute Bayes factor
  lbeta.xa <- sum(lgamma(alphas + counts)) - lgamma(sum(alphas + counts))
  lbeta.a  <- sum(lgamma(alphas)) - lgamma(sum(alphas))
  
#  return(lbeta.a)
  
  # in this case, counts*log(thetas) should be zero, omit to avoid numerical issue with log(0)
  if (any(rowSums(cbind(thetas, counts)) == 0)) {
    LogBF10 <- (lbeta.xa-lbeta.a)
  } else {
    LogBF10 <- (lbeta.xa-lbeta.a) + (0 - sum(counts * log(thetas)))
  }
  
  BF <- data.frame(LogBF10 = LogBF10,
                   BF10    = exp(LogBF10),
                   BF01    = 1/exp(LogBF10))
  
  return(BF$BF10)
  return(list(BF       = BF,
              expected = expected))
}

bayesfactorversion <- function(alphas, counts, thetas) {
# Prior setup
prior_concentration = sum(alphas)
# null 
# if needed: rescale
if(sum(thetas) != 1) {
  p0 <- thetas/sum(thetas)
} else {
  p0 <- thetas
}

N <- sum(counts)
y <- counts


# Visualize prior density; vis really only works for 3 probabilities
# x = MCMCpack::rdirichlet(10000, prior_concentration * p0)

# (log) prob of data under null
pr_y_h0 = dmultinom(x = y, prob = p0, log = TRUE)


# Estimate log prob of data under null with Monte Carlo
M = 100000
p1s = MCMCpack::rdirichlet(M, prior_concentration * p0)
tmp_pr_h1 = sapply(1:M, function(i) dmultinom(x = y, prob = p1s[i,], log = TRUE))
pr_y_h1 = BayesFactor::logMeanExpLogs(tmp_pr_h1)

bf_10 = exp(pr_y_h1 - pr_y_h0)
bf_10
}

fixedcounts <- c(15, 12, 5)
fixedthetas <- c(11,11,11)
jaspversion(alphas = c(1, 1, 1), counts = fixedcounts, thetas = fixedthetas)
#> [1] 0.9435466
bayesfactorversion(alphas = c(1, 1, 1), counts = fixedcounts, thetas = fixedthetas)
#> [1] 0.9509458
jaspversion(alphas = c(2, 2, 2), counts = fixedcounts, thetas = fixedthetas)
#> [1] 1.515503
bayesfactorversion(alphas = c(2, 2, 2), counts = fixedcounts, thetas = fixedthetas)
#> [1] 1.514268
jaspversion(alphas = c(4, 1, 1), counts = fixedcounts, thetas = fixedthetas)
#> [1] 0.9909061
bayesfactorversion(alphas = c(4, 1, 1), counts = fixedcounts, thetas = fixedthetas)
#> [1] 1.50119
jaspversion(alphas = c(1, 1, 4), counts = fixedcounts, thetas = fixedthetas)
#> [1] 0.06800336
bayesfactorversion(alphas = c(1, 1, 4), counts = fixedcounts, thetas = fixedthetas)
#> [1] 1.52232
```

<sup>Created on 2019-06-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
Thanks for the detailed comparison of these two implementations! I would definitely vote for the JASP implementation then. It's faster and also gets rid of MCMC dependency. 

Do you want to make a PR or should I just replace the existing code I have from Richard with the one you have provided here for the JASP version?

**Comment by ibecav** [comment]
You go right ahead please. I just lifted the code out of the larger Jasp file I listed above. Alpha counts and thetas all have to be vectors of the same length.  Counts is required from the user (likely easiest to pass from a base r table cmd. Alpha and counts must be integers. Theta has code to coerce to sum to 1. Default for alpha and theta should be a vector or 1s the same length as counts. If the user does supply alphas or thetas where not every entry in the vector is identical order does matter and they nneed to take care to specify the proper order.

As to credible intervals Jasp is just calculating them identically as you would for conf intervals

The reprex by the way is actually the mtcars$gear data

**Comment by IndrajeetPatil** [comment]
@ibecav I tried to add this but I feel like I am doing something incorrectly. I get a flood of `warnings` when I use the function inside another function like `subtitle_contingency_tab()`. 

Do you want to make a PR instead?

**Comment by ibecav** [comment]
No thank you.  I doubt I will ever again submit a formal PR after the last one.

You didn't send me enough info to see what was generating the warnings() so I took your current helpers_ggpiestats_subtitles.R and hacked it up so that  it will generate bayes factors for GoF where k>2.  Some of your error checking I didn't understand at all so I ripped it out.  Left to you to figure out how to collect prior.counts from end user for now I set them to the default 1.

Hope this helps.  I'll drop the code here, if it's easier I'm happy to email it to you...  Obviously there's some other cleanup and decisions you can make

#' @title Subtitle for categorical tests
#' @description Making text subtitle for contingency analysis (Pearson's
#'   chi-square test for independence for between-subjects design or McNemar's
#'   test for within-subjects design) or goodness of fit test for a single
#'   categorical variable.
#' @author Indrajeet Patil
#'
#' @param main The variable to use as the **rows** in the contingency table.
#' @param condition The variable to use as the **columns** in the contingency
#'   table. Default is `NULL`. If `NULL`, one-sample proportion test (a goodness
#'   of fit test) will be run for the `main` variable. Otherwise an appropriate
#'   association test will be run.
#' @param counts A string naming a variable in data containing counts, or `NULL`
#'   if each row represents a single observation (Default).
#' @param paired Logical indicating whether data came from a within-subjects or
#'   repeated measures design study (Default: `FALSE`). If `TRUE`, McNemar's
#'   test subtitle will be returned. If `FALSE`, Pearson's chi-square test will
#'   be returned.
#' @param stat.title Title for the effect being investigated with the chi-square
#'   test. The default is `NULL`, i.e. no title will be added to describe the
#'   effect being shown. An example of a `stat.title` argument will be something
#'   like `"main x condition"` or `"interaction"`.
#' @param bias.correct If `TRUE`, a bias correction will be applied to Cramer's
#'   *V*.
#' @param ratio A vector of proportions: the expected proportions for the
#'   proportion test (should sum to 1). Default is `NULL`, which means the null
#'   is equal theoretical proportions across the levels of the nominal variable.
#'   This means if there are two levels this will be `ratio = c(0.5,0.5)` or if
#'   there are four levels this will be `ratio = c(0.25,0.25,0.25,0.25)`, etc.
#' @param legend.title Title text for the legend.
#' @param ... Additional arguments (currently ignored).
#' @inheritParams t1way_ci
#' @inheritParams subtitle_t_parametric
#' @inheritParams stats::chisq.test
#' @inheritParams subtitle_anova_parametric
#'
#' @importFrom dplyr select mutate mutate_at union rename filter
#' @importFrom ellipsis check_dots_used
#' @importFrom rlang !! enquo as_name ensym
#' @importFrom tibble tribble as_tibble
#' @importFrom tidyr uncount drop_na
#' @importFrom stats mcnemar.test chisq.test
#' @importFrom rcompanion cramerV cohenG cramerVFit
#'
#' @seealso \code{\link{ggpiestats}}
#'
#' @details For more details about how the effect sizes and their confidence
#'   intervals were computed, see documentation in `?rcompanion::cramerV`,
#'   `?rcompanion::cramerVFit`, and `?rcompanion::cohenG`.
#'
#' @examples
#'
#' # ------------------------ association tests -----------------------------
#'
#' set.seed(123)
#'
#' # without counts data
#' ggstatsplot::subtitle_contingency_tab(
#'   data = mtcars,
#'   main = am,
#'   condition = cyl,
#'   nboot = 15
#' )
#'
#' # with counts data
#' # in case of no variation, a `NULL` will be returned.
#' library(jmv)
#'
#' as.data.frame(HairEyeColor) %>%
#'   dplyr::filter(.data = ., Sex == "Male") %>%
#'   subtitle_contingency_tab(
#'     data = .,
#'     main = Hair,
#'     condition = Sex,
#'     counts = Freq
#'   )
#'
#' # ------------------------ goodness of fit tests ---------------------------
#'
#' # for reproducibility
#' set.seed(123)
#'
#' # with counts
#' subtitle_contingency_tab(
#'   data = as.data.frame(HairEyeColor),
#'   main = Eye,
#'   counts = Freq,
#'   ratio = c(0.2, 0.2, 0.3, 0.3)
#' )
#'
#' # in case of no variation, only sample size will be shown
#' subtitle_contingency_tab(
#'   data = cbind.data.frame(x = rep("a", 10)),
#'   main = x
#' )
#' @export

# function body
subtitle_contingency_tab <- function(data,
                                     main,
                                     condition = NULL,
                                     counts = NULL,
                                     ratio = NULL,
                                     nboot = 100,
                                     paired = FALSE,
                                     stat.title = NULL,
                                     legend.title = NULL,
                                     conf.level = 0.95,
                                     conf.type = "norm",
                                     simulate.p.value = FALSE,
                                     B = 2000,
                                     bias.correct = FALSE,
                                     k = 2,
                                     messages = TRUE,
                                     ...) {
  ellipsis::check_dots_used()

  # =============================== dataframe ================================

  # creating a dataframe
  data %<>%
    dplyr::select(
      .data = .,
      main = {{ main }},
#      condition = {{ condition }},
      counts = {{ counts }}
    ) %>%
    tidyr::drop_na(data = .)

  # main and condition need to be a factor for this analysis
  # also drop the unused levels of the factors

  # main
  data %<>%
    dplyr::mutate(.data = ., main = droplevels(as.factor(main))) %>%
    tibble::as_tibble(x = .)


  # ============================ converting counts ===========================

  # untable the dataframe based on the count for each observation
  if ("counts" %in% names(data)) {
    data %<>%
      tidyr::uncount(
        data = .,
        weights = counts,
        .remove = TRUE,
        .id = "id"
      ) %>%
      tibble::as_tibble(.)
  }

  # =============================== Pearson's chi-square =====================

  # sample size
  sample_size <- nrow(data)

  # ratio
  if (is.null(ratio)) {
    ratio <- rep(1 / length(table(data$main)), length(table(data$main)))
  }
  if(sum(ratio) != 1) {
    ratio <- ratio/sum(ratio)
  }

  prior.counts <- rep(1, length(table(data$main)))

  if (!identical(length(prior.counts), length(table(data$main)))) {

  }

  tcounts <- table(data$main)

    # ================= bayes goodness of fit test ========================

  # expected counts under the null hypothesis (Binomial median)
  expected <- setNames(sum(tcounts)*ratio, names(tcounts))

  # compute Bayes factor
  lbeta.xa <- sum(lgamma(prior.counts + tcounts)) - lgamma(sum(prior.counts + tcounts))
  lbeta.a  <- sum(lgamma(prior.counts)) - lgamma(sum(prior.counts))

  #  return(lbeta.a)

  # in this case, tcounts*log(ratio) should be zero, omit to avoid numerical issue with log(0)
  if (any(rowSums(cbind(ratio, tcounts)) == 0)) {
    LogBF10 <- (lbeta.xa-lbeta.a)
  } else {
    LogBF10 <- (lbeta.xa-lbeta.a) + (0 - sum(tcounts * log(ratio)))
  }

  BF <- data.frame(LogBF10 = LogBF10,
                   BF10    = exp(LogBF10),
                   BF01    = 1/exp(LogBF10))

#  return(BF$BF10)
  return(list(BF       = BF,
              expected = expected))
    # running chi-squared test
    stats_df <- chisq.test(
          x = table(data$main),
          y = NULL,
          correct = FALSE,
          p = ratio,
          rescale.p = FALSE,
          simulate.p.value = simulate.p.value,
          B = B
      )
# return(stats_df)
    # if for some reason chi square bombs
    # then no subtitle is needed
    if (is.nan(stats_df$statistic[[1]])) {
      subtitle <-
        substitute(
          expr = paste(italic("n"), " = ", n),
          env = list(n = sample_size)
        )

      # display message
      message(cat(
        crayon::red("Warning: "),
        crayon::blue("Can't run chi square on "),
        crayon::yellow(legend.title),
        crayon::blue(" sorry."),
        sep = ""
      ))

      # return early
      return(subtitle)
    } else {

      # tidying up the results
      stats_df <- broomExtra::tidy(stats_df)

      # dataframe with effect size and its confidence intervals
      effsize_df <- rcompanion::cramerVFit(
        x = as.vector(table(data$main)),
        p = ratio,
        ci = TRUE,
        conf = conf.level,
        type = conf.type,
        R = nboot,
        histogram = FALSE,
        digits = 5
      ) %>%
        tibble::as_tibble(x = .) %>%
        dplyr::rename(
          .data = .,
          estimate = Cramer.V,
          conf.low = lower.ci,
          conf.high = upper.ci
        )

      # effect size is Cramer's V
      effsize.text <- quote(italic("V")["Cramer"])
      statistic.text <- quote(chi["gof"]^2)
    }


  # preparing subtitle
  subtitle <- subtitle_template(
    no.parameters = 1L,
    stat.title = stat.title,
    statistic.text = statistic.text,
    statistic = stats_df$statistic[[1]],
    parameter = stats_df$parameter[[1]],
    p.value = stats_df$p.value[[1]],
    effsize.text = effsize.text,
    effsize.estimate = effsize_df$estimate[[1]],
    effsize.LL = effsize_df$conf.low[[1]],
    effsize.UL = effsize_df$conf.high[[1]],
    n = sample_size,
    conf.level = conf.level,
    k = k,
    k.parameter = 0L
  )

  # message about effect size measure
  if (isTRUE(messages)) {
    effsize_ci_message(nboot = nboot, conf.level = conf.level)
  }

  # return the subtitle
  return(subtitle)
}

#' @rdname subtitle_contingency_tab
#' @aliases subtitle_contingency_tab
#' @export

subtitle_onesample_proptest <- subtitle_contingency_tab

**Pull request merged**
