### PR TITLE
Issue #165 changes

### PR DESCRIPTION
**Pull request by ibecav**
No idea what changed that it won't auto merge

### CODE REVIEW

**Comment by ibecav** [comment]
No idea what you changed or how to resilve

**Comment by IndrajeetPatil** [comment]
We had a few conflicts with my recent commits that I had to manually resolve. I had added `...` to all subtitle helper functions which were missing in your branch. 

I've manually changed this.

**Comment by IndrajeetPatil** [comment]
The builds are going to fail because the tests for `subtitle_mann_nonparametric` wasn't changed. I am still merging this; I will change it in the master itself.

**Comment by IndrajeetPatil** [comment]
Please catch up with the `master` branch so that there won't be any merge conflicts anymore.

**Comment by ibecav** [comment]
I do try and stay synched at all times.  The problem is if that I have some work that takes quit a bit of time we wind up slightly out of synch.  Just deleted my branch resycnched and added ellipsis

**Comment by IndrajeetPatil** [comment]
Cool.

What issue do you plan to work on next? I won't touch those files. Trying to get as much done as possible today to try to submit the new version tomorrow or day after.

**Comment by ibecav** [comment]
Right also worried about time pressure.  Did you delete or change a bunch of lines I had commented out in test_effsize_t_parametric? I had left them commented because they highlighted the issue with abs(d).

**Comment by IndrajeetPatil** [comment]
Oops, sorry about that; didn't realize they were commented out for a reason. I thought you just wanted to have them as a reference to compare with the new values.

Anyway, you can find the commented lines in this commit:
https://github.com/IndrajeetPatil/ggstatsplot/commit/1ca3576ca12d2f995f52699ec335d18277d74ce7#diff-b2ecbe4080f27f2330afbd1a32c3f1a2

**Pull request merged**
