### PR TITLE
Test for subtitle_anova_parametric

### PR DESCRIPTION
**Pull request by ibecav**
Per your request I'm adding some tests.  Please take a look at this first one.  They're a bit different because the function actually returns a `call` object. So I'm testing the complete `call` which has a bunch of formatting in it as well as few key substrings which are actually the crucial numbers generated by the actual tests.

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Cool, this all looks good to me. 

But do you think we should be usingt the entire `movies_long` dataset here? It's a massive dataset (_n_ = 2433) and the test will take (relatively) long time to run. Maybe it will be better to use a smaller subset (~10%) of the data? 

Right now, we don't have many tests so `CRAN` runtime is not that long. But, as we keep adding more tests, the check time is going to increase and then that can cause headaches with the `R CMD CHECK`. So better to protect ourselves from that possibility from early on.

**Comment by ibecav** [comment]
I did think about run time and even microbenchmarked it (about 18 milliseconds) even if you increase nboot you're okay.  Since it doesn't involve any actual plotting this is very fast even on a large number of rows.

**Comment by IndrajeetPatil** [comment]
Oh, you are right! Completely forgot that there are no plots being generated here. Cool, merging now.

**Comment by IndrajeetPatil** [comment]
There was already one test for parametric ANOVA subtitles. But it was with data that had missing values and also didn't check the complete `call`. So your addition is a nice complementary test:
https://github.com/IndrajeetPatil/ggstatsplot/blob/master/tests/testthat/test_anova_subtitles.R

**Pull request merged**
