### PR TITLE
grouped_ggbarstats ready

### PR DESCRIPTION
**Pull request by ibecav**
Should be all set including doco.  Reprex of the complex example included.

I notice that in `data.label` you  put back in the carriage return `\n` between the percent and the count when `"both"` are requested.  I had very deliberately removed it.  As the reprex clearly shows vertical space is at a premium on stacked bar charts adding that line break is going to cause overlap in almost all cases.  There is usually much more horizontal space available so please.

``` r
library(ggstatsplot)
# the following will take slightly more amount of time
## Not run: 
# for reproducibility
set.seed(123)

# let's create a smaller dataframe
diamonds_short <- ggplot2::diamonds %>%
  dplyr::filter(.data = ., cut %in% c("Very Good", "Ideal")) %>%
  dplyr::filter(.data = ., clarity %in% c("SI1", "SI2", "VS1", "VS2", "VVS1", "VVS2")) %>%
  dplyr::sample_frac(tbl = ., size = 0.10)

# plot
ggstatsplot::grouped_ggbarstats(
  data = diamonds_short,
  main = color,
  condition = clarity,
  grouping.var = cut,
  bf.message = TRUE,
  sampling.plan = "poisson",
  title.prefix = "Quality",
  data.label = "both",
  messages = FALSE,
  perc.k = 1,
  nrow = 2
)
#> Warning in stats::chisq.test(x = data$main, y = data$condition, correct =
#> FALSE, : Chi-squared approximation may be incorrect
```

<sup>Created on 2019-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
I buy that argument. I had to modify it to be consistent with `ggpiestats` where not having `\n` led to an overlap of two labels across slices. I am now doing this using a common function (https://github.com/IndrajeetPatil/ggstatsplot/blob/master/R/helpers_ggcatstats.R) and so both of them are behaving the same way. That said, I know a way around this so that, as a default, `ggpiestats` will have `\n` in the label, while `ggbarstats` will not. I will implement it **after the current PR is merged**. 

By the way, the tests are failing because some of the `formals` present for `ggbarstats` are not present in its `grouped_` variant. Can you have a look which ones are missing?

**Comment by IndrajeetPatil** [comment]
No, this still won't solve the issue. 

The problem is that `grouped_` variants of functions are not supposed to have `title = NULL` formals (because `title.prefix` is used instead), but it is currently included in `grouped_ggbarstats`-
https://github.com/ibecav/ggstatsplot/blob/0e30921dc54fb7974c9acade362b4d1a5720a0dc/R/grouped_ggbarstats.R#L93

Once you remove it, this should work.

**Comment by ibecav** [comment]
Ah I see, learn something everyday.  PR updated.

**Comment by IndrajeetPatil** [comment]
Like you wanted, the defaults for `"both"` are different for these two functions-
``` r
set.seed(123)
library(ggstatsplot)

ggstatsplot::combine_plots(
  ggpiestats(mtcars, am, cyl, slice.label = "both", messages = FALSE),
  ggbarstats(mtcars, am, cyl, data.label = "both", messages = FALSE),
  labels = c("(a)", "(b)"),
  nrow = 1
)
#> Warning in stats::chisq.test(x = data$main, y = data$condition, correct =
#> FALSE, : Chi-squared approximation may be incorrect

#> Warning in stats::chisq.test(x = data$main, y = data$condition, correct =
#> FALSE, : Chi-squared approximation may be incorrect
```



<sup>Created on 2019-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ibecav** [comment]
Thank you

**Pull request merged**
